import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.tokyo-ct.ac.jp/">NITTC!</a>
        </h1>

        <p className={styles.description}>
          Escape from classroom{' '}
          <code className={styles.code}>made by 1-5</code>
        </p>
        <div className={styles.wrapper}>
          <p className={styles.glitch}>
            {/* Text Animation */}
            <span className={styles.text}><span className={styles.bomb}>爆弾</span>を探し、生き残れ！</span>
            </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
